---
- name: restart jenkins
  become: yes
  service: name=jenkins state=restarted

- name: configure default users
  become: yes
  template:
    src: basic-security.groovy
    dest: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775
  register: jenkins_users_config
